### ISSUE TITLE
Multi-line completions

### ISSUE THREAD

**Issue by lemontheme** [sourcegraph/sg.nvim#197]
I've been testing this plugin on and off. I'm mostly interested in Cody. On the whole I'd say the plugin experience is more cohesive than what's offered by currently available Copilot plugins for neovim. 

There's just one thing that stands out as lacking: multiline completions, i.e. suggested completions can span multiple lines. Today, each line needs to be completed indivudally. For a long block of code, that translates to a lot of completion steps.

Judging by [this comment](https://github.com/sourcegraph/sg.nvim/issues/171#issuecomment-1879172738) under #171, I'm guessing this is something the plugin author(s) are already aware of. Just seemed handy to have a clearly named issue where I and others can follow the status of this feature's development. Feel free to close it as a duplicate, however.

**Comment by Doctor-Scott** [comment]
Also noticed this, could just be my config though, using cody with cmp.nvim
It would be good to see a more detailed example of how to get multiline completion working if they are supposed to be in neovim

**Comment by tjdevries** [comment]
With the latest updates, multi-line completions will trigger for certain filetypes. After #243 , we should see that expand as we'll be picking up more options from cody.

I'll close for now because multi-line completions are supported for many of the basic cases (you'll have to accept the completion to apply the multi-line completion)
